variables:
  QUICKLISP_ADD_TO_INIT_FILE: "true"
  QUICKLISP_DIST_VERSION: latest

image: clfoundation/$LISP:$IMAGE_TAG

stages:
  - test
  - build

before_script:
  - install-quicklisp

.test:
  stage: test
  script:
    - make test

.build:
  stage: build
  script:
    - make build
  only:
    - tags

sbcl test:
  extends: .test
  variables:
    LISP: sbcl
    IMAGE_TAG: latest

linux build:
  extends: .build
  variables:
    LISP: sbcl
    IMAGE_TAG: latest
  artifacts:
    paths:
      - build/line-parser

windows build:
  extends: .build
  variables:
    LISP: sbcl
    IMAGE_TAG: latest-windowsservercore
  artifacts:
    paths:
      - build/line-parser-windows